---
# Playbook for installing Hyrax IR Stack.
- name: Install Hyrax on remote hosts.
  hosts: hyrax_0,hyrax_1
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/{{ ansible_distribution }}.yml"
  roles:
    - hyrax
    - apache-shib
    - notch8.ssh
