---
# Playbook for installing Hyrax IR Stack.
- name: Install Digital Archives Worker on remote hosts.
  hosts: digital_archives_worker
  become: yes
  vars_files:
    - "vars/common.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/digital_archives.yml"
  roles:
    - hyrax
    - notch8.ssh
