---
- name: Populate service facts
  service_facts:

- name: Restart and enable puma
  service:
    name: puma
    state: restarted
    enabled: yes
  when: "'puma' in services"

- name: Restart and enable sidekiq
  service:
    name: sidekiq
    state: restarted
    enabled: yes
  when: "'sidekiq' in services"

- name: Restart Apache
  service:
    name: httpd
    state: restarted
    enabled: yes
  when: "'httpd' in services"
